from . import education_student
from . import student_level
from . import education_school
from . import education_class
from . import education_class_group
from . import res_partner
from . import education_student_copy
from . import base_education
from . import education_class_size